config/routes.rb
Rails.application.routes.draw do
#   devise_for :views
#   devise_for :users
#   get "home/index"
#   root to: "home#index"
# end
# Rails.application.routes.draw do
  # devise_for :users
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :views
  get "home/index"
  root to: "home#index"

  resources :sales, only: [:index, :show] do
    get 'all', to: 'sales#all', on: :collection
  end

  resources :customers, only: [:new, :create, :edit, :update, :show, :index, :destroy]
  resources :reports, only: [:index, :show, :edit, :update]
  resources :orders, only: [:new, :create, :update, :show, :destroy] do
    collection do
      get 'new/:items', :action => 'new', :as => 'item_to_be_added_to'
      get 'edit/:items', :action => 'new_customer', :as => 'new_customer_for'
      delete 'remove/:items, :item', :action => 'remove_item', :as => 'remove_item_from'
    end
    resources :receipts, only: [:new], defaults: { format: :pdf }
    resources :payments, only: [:new, :create]
    resources :items, only: [:new, :create, :destroy]
  end
  resources :payments do
    collection do
      get 'new/:items, :customer', :action => 'new_order_payment', :as => 'new_order'
      get 'new/:items', :action => 'new_order_payment', :as => 'new_order_without_customer'
    end
  end

  resources :items, only: [:create]
  resources :catalogue, only: [:index]
  resources :suppliers, only: [:index, :new, :create, :show, :edit, :update]

  namespace :catalogue do
    resources :suppliers, only: [:index, :new, :create, :show] do
      resources :products, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
        resources :variants, only: [:create, :edit, :update, :destroy, :show] do
          get :print, on: :member
        end
        resource :variant do
          collection do
            get "new/:variant_attributes", :action => 'new', :as => 'new', :defaults => { :variant_attributes => "" }
          end
        end
        resources :product_attributes, only: [:new, :create]
        resources :product_attribute_types, only: [:index, :new, :create, :destroy]
      end
    end
    resources :variants do
      collection do
        get 'index/:results, :query_params', :action => 'index', :as => 'index'
        post 'search', :action => 'search', :as => 'search'
      end
    end
  end

  namespace :inventory do
    resources :suppliers, only: [:index, :new, :create, :show] do
      resources :products, only: [] do
        resources :variants, only: [] do
          resources :adjustments, only: [:new, :create, :index]
        end
      end
    end
  end
  resources :inventories, only: [:index]
end

app/controllers/catalogue/product_attribute_types_controller.rb
# frozen_string_literal: true

class Catalogue::ProductAttributeTypesController < ApplicationController
  before_action :supplier_id, :product_id, only: %i[index new create destroy]
  before_action :product_attribute_type, only: %i[destroy]

  def index
    @product_attribute_types = ProductAttributeType.all
  end

  def new
    @product_attribute_type = ProductAttributeType.new
  end

  def create
    @product_attribute_type = ProductAttributeType.new(product_attribute_type_params)
    return render(:new, status: :unprocessable_entity) unless @product_attribute_type.save

    redirect_to new_catalogue_supplier_product_variant_path(supplier_id, product_id)
  end

  def destroy
    flash.now.alert = if product_attribute_type&.remove!
                        'Attribute Type was removed'
                      else
                        'Unable to remove the Attribute Type'
                      end
    redirect_to catalogue_supplier_product_product_attribute_types_path(@supplier_id, @product_id)
  end

  private

  def product_attribute_type
    @product_attribute_type = ProductAttributeType.find_by(id: params['id'])
  end

  def supplier_id
    @supplier_id ||= params['supplier_id']
  end

  def product_id
    @product_id ||= params['product_id']
  end

  def product_attribute_type_params
    params.require(:product_attribute_type).permit(:name)
  end
end

app/controllers/catalogue/product_attributes_controller.rb
# frozen_string_literal: true

class Catalogue::ProductAttributesController < ApplicationController
  before_action :authenticate_user!
  before_action :attribute_types, :supplier_id, :product_id, only: %i[new create]

  def new
    @product_attribute = ProductAttribute.new
  end

  def create
    @product_attribute = ProductAttribute.new(product_attribute_params)
    return render(:new, status: :unprocessable_entity) unless @product_attribute.save

    redirect_to new_catalogue_supplier_product_variant_path(supplier_id, product_id)
  end

  private

  def attribute_types
    @attribute_types = ProductAttribute.valid_attribute_types
  end

  def supplier_id
    @supplier_id ||= params['supplier_id']
  end

  def product_id
    @product_id ||= params['product_id']
  end

  def product_attribute_params
    params.require(:product_attribute).permit(:name, :value)
  end
end

app/controllers/catalogue/products_controller.rb
# frozen_string_literal: true

class Catalogue::ProductsController < ApplicationController
  before_action :authenticate_user!
  before_action :sanitize_params, only: %i[create update]
  before_action :product_with_sku_code, only: [:new]
  before_action :calculation_methods, only: %i[new create edit update]
  before_action :existing_product, only: %i[edit update destroy show]

  def show; end

  def new
    session.delete(:product_params)
  end

  def edit; end

  def create
    session[:product_params] = params[:product] #gets the params passed into create and pushes them back into new

    if (valid_cost_price? || valid_retail_price?) && product_params[:markup].present?
      new_product = supplier.products.new(product_params) if session[:product_params].present?
      if new_product.save
        session.delete(:product_params)
        return redirect_to catalogue_supplier_path(supplier.id)
      end
    end
    redirect_to new_catalogue_supplier_product_path(supplier.id)
  end

  def update
    return render(:edit, status: :unprocessable_entity) unless @existing_product.update(product_params)

    redirect_to catalogue_supplier_path(supplier.id)
  end

  # rubocop:disable Layout/LineLength
  def destroy
    alert_message = 'Product and all of its Variants have been deleted'
    if @existing_product.stock? || @existing_product.been_sold?
      alert_message = 'Unable to delete Product, a variant of this Product has existing stock or has been sold one or more times. Product has been unpublished instead.'
      @existing_product.update(publish: false)
    else
      @existing_product.remove!
    end

    flash[:notice] = alert_message
    redirect_to catalogue_supplier_path(supplier.id)
  end
  # rubocop:enable Layout/LineLength

  private

  def valid_retail_price?
    product_params[:retail_price].present? && product_params[:retail_price] > 0
  end

  def valid_cost_price?
    product_params[:cost_price].present? && product_params[:cost_price] > 0
  end

  def calculation_methods
    @calculation_methods = [OpenStruct.new(name: 'Cost Price Method', value: 0), OpenStruct.new(name: 'Retail Price Method', value: 1)]
  end

  def existing_product
    @existing_product = supplier.products.find_by(id: params['id'])
  end

  def product
    @product ||= supplier.products.new
  end

  def product_with_sku_code
    return product.assign_attributes(session[:product_params]) if session[:product_params].present?

    product.sku_code = sku_code
    product
  end

  def sku_code
    @sku_code ||= @product.generated_sku
  end

  def sanitize_params
    params.require(:product).permit(:supplier_id, :accounting_code_id, :title, :description, :notes, :sku_code, :publish, :markup, :cost_price)

    params[:product]['markup'] = markup
    params[:product]['publish'] = publish
    params[:product]['cost_price'] = cost_price
    params[:product]['retail_price'] = retail_price
    params[:product]['price_calc_method'] = price_calc_method
  end

  def unmatched_params
    @unmatched_params ||= params.require(:product).extract!(:publish, :markup, :cost_price, :retail_price, :price_calc_method)
  end

  def cost_price
    (unmatched_params['cost_price'].gsub(/[^0-9.]/, '').to_f * 100).to_i if unmatched_params['cost_price']
  end

  def retail_price
    (unmatched_params['retail_price'].gsub(/[^0-9.]/, '').to_f * 100).to_i if unmatched_params['retail_price']
  end

  def price_calc_method
    if unmatched_params['price_calc_method'].blank?
      nil
    else
      unmatched_params['price_calc_method'].to_i
    end
  end

  def markup
    unmatched_params['markup'].present? ? unmatched_params['markup'].gsub(/[^0-9]/, '') : nil
  end

  def publish
    unmatched_params['publish'] == 'Yes'
  end

  def product_params
    params.require(:product).permit(:supplier_id, :accounting_code_id, :title, :description, :notes, :sku_code, :publish, :markup, :cost_price,
                                    :price_calc_method, :retail_price)
  end

  def supplier
    @supplier ||= Supplier.find_by(id: supplier_id)
  end

  def supplier_id
    @supplier_id = params['supplier_id']
  end
end

app/controllers/catalogue/suppliers_controller.rb
# frozen_string_literal: true

class Catalogue::SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :supplier, only: %i[index create]

  def index; end

  def show
    @supplier = existing_supplier(id: params['id'])
    @products = @supplier.products
  end

  def create
    if existing_supplier.present?
      redirect_to catalogue_supplier_path(existing_supplier.id)
    else
      flash.now.alert = 'Please select a supplier from the list'
      render(:index, status: :unprocessable_entity)
    end
  end

  private

  def supplier
    @supplier ||= Supplier.new
  end

  def existing_supplier(id: nil)
    supplier_id = id || supplier_params[:id]
    @existing_supplier = Supplier.find_by(id: supplier_id) if supplier_id.present?
  end

  def supplier_params
    params.require(:supplier).permit(:id)
  end
end

app/controllers/catalogue_controller.rb
# frozen_string_literal: true

class CatalogueController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/helpers/catalogue/product_attribute_types_helper.rb
# frozen_string_literal: true

module Catalogue::ProductAttributeTypesHelper
end

app/helpers/catalogue/product_attributes_helper.rb
# frozen_string_literal: true

module Catalogue::ProductAttributesHelper
end

app/helpers/catalogue/products_helper.rb
# frozen_string_literal: true

module Catalogue::ProductsHelper
end

app/helpers/catalogue/suppliers_helper.rb
# frozen_string_literal: true

module Catalogue::SuppliersHelper
end

app/helpers/catalogue/variants_helper.rb
# frozen_string_literal: true

module Catalogue::VariantsHelper
end

app/helpers/catalogue_helper.rb
# frozen_string_literal: true

module CatalogueHelper
end

app/views/catalogue/variants/edit.html.erb
<div class="p-12 mx-auto text-gray-800 max-w-7xl">
  <h2>Edit Variant for Product: <%= @existing_variant.product.title %></h2>

  <% if @existing_variant.errors.any? %>
    <% @existing_variant.errors.full_messages.each do |message|%>
       <p class="text-red-700 text-base"><%= message %> </p>
    <%end%>
  <%end%>
  <br />
  <%= simple_form_for @existing_variant, builder: TailwindFormBuilder, class: "mt-6", url: catalogue_supplier_product_variant_path do |f| %>
    <%= f.hidden_field :quantity, value: 0 %>

    <% index = 0 %>
    <h5><%= f.label "Please select applicable attributes for this variant" %></h5>
    <%= f.simple_fields_for :product_attributes_variants do |attribute_fields| %>
      <% if index == 0 || index % 3 == 0 %>
        <div class="row">
      <% end %>
          <div class="col-4">
            <%= attribute_fields.label @attribute_types[index] %>
            <%= attribute_fields.collection_select :product_attribute_id, ProductAttribute.atributes_for(@attribute_types[index]).order(:value),:id, :display_value, include_blank: false %>
          </div>
        <% index += 1 %>
    <% end %>
    <% index %>
    </div>
    <% (index / 3).times do %>
      <!-- </div> -->
    <% end %>

    <br />
    <%= link_to '<button type="button" class="btn btn-outline-primary">Add Attribute Values</button>'.html_safe, new_catalogue_supplier_product_product_attribute_path(@product.supplier.id, @product) %>
    <%= link_to '<button type="button" class="btn btn-outline-secondary">New Attribute Type</button>'.html_safe, new_catalogue_supplier_product_product_attribute_type_path(@product.supplier.id, @product) %>
    <%= link_to '<button type="button" class="btn btn-outline-danger">Remove Attribute Type</button>'.html_safe, catalogue_supplier_product_product_attribute_types_path(@product.supplier.id, @product) %>
    <br />
    <br />
     <div class="row">
      <div class="col-6">
        <%= f.label "SKU Code" %>
        <%= f.text_field :sku_code, value: @existing_variant.sku_code, readonly: true %>
      </div>
      <div class="col-6">
        <div><%= f.label "Description" %>
          <%= @existing_variant.product.description %>
        </div>
      </div>
    </div>
    <!-- drop down use same price and markup as product (show in 3 columns) -->
    <!-- if the user says no to above show the select method, then as per product -->
    <br />
    <h5><%= f.label "Price information for the parent product of this variant" %></h5>
     <div class="row">
      <div class="col-4">
        <div><%= f.label "Product Cost Price" %>
        <%= @existing_variant.product.display_cost_price %></div>
      </div>
      <div class="col-4">
        <div><%= f.label "Product Retail Price" %>
        <%= @existing_variant.product.display_total_retail_price_including_tax %></div>
      </div>
      <div class="col-4">
        <div><%= f.label "Product Markup Percentage" %>
        <%= @existing_variant.product.display_markup %></div>
      </div>
    </div>
    <br />
    <div data-controller="product">
      <div class="d-none" data-product-target="registeredForSalesTax"><%= @existing_variant.product.supplier. sales_tax_registered %></div>
      <%= f.label "Do you want to use these product prices and markup percentage for the variant you are about to create?" %>
      <br />
      <% use_product_prices = [OpenStruct.new(name: 'Yes same as the Product', value: 0), OpenStruct.new(name: 'No this Variant has different prices and / or markup', value: 1)] %>
      <%= f.collection_select :price_calc_method, use_product_prices, :value, :name, {include_blank: true, selected: @existing_variant.use_product_details_drop_down_value }, data: { action: "change->product#useProductPricing", target: "product.usesProductPricing" } %>
      <br />
      <br />
      <div class="d-none" data-product-target="selectCalculateMethodSection">
        <%= f.label "How would you like to calculate the prices?" %>
        <br />
        <%= f.collection_select :price_calc_method, @calculation_methods, :value, :name, {include_blank: true, selected: @existing_variant.selected_price_calc_method_id }, data: { action: "change->product#selectSection", target: "product.priceCalcMethod" } %>
        <br />
        <br />

        <!-- section for entering amounts via the retail price method -->
        <div class="d-none" data-product-target="calculateRetailPriceSection">
          <br />
          <div class="row">
            <div class="col-6">
              <%= f.label "Total Retail Price (including sales tax)" %>
              <%= f.text_field :retail_price, placeholder: 'the amount you intend to sell the product for and place on price labels', value: @existing_variant.display_total_retail_price_including_tax, data: { action: "change->product#retailPriceDataEntered", target: "product.retailPrice" } %>
            </div>
            <div class="col-6">
              <%= f.label "Markup percentage" %>
              <%= f.text_field :markup, placeholder: 'enter the markup percentage you would like to determine the cost price', value: @existing_variant.display_markup, data: { action: "change->product#retailPriceDataEntered", target: "product.retailPercentage" } %>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-4">
              <div class="cost_price">Suppliers Cost Price (excl tax)</div>
              <div class="cost_price" data-product-target="retailCalculatedCostPrice">
                $ -
              </div>
            </div>
             <div class="col-4">
              <div class="cost_price">Suppliers Tax Amount</div>
              <div class="cost_price" data-product-target="retailCalculatedCostPriceTax">
                $ -
              </div>
            </div>
            <div class="col-4">
              <div class="cost_price">Suppliers Total Cost Price (incl tax)</div>
              <div class="cost_price" data-product-target="retailCalculatedCostPriceTotal">
                $ -
              </div>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-4">
              <div class="retail_price">Retail Price (excl tax)</div>
              <div class="retail_price" data-product-target="retailCalculatedRetailPrice">
                $ -
              </div>
            </div>
             <div class="col-4">
              <div class="retail_price">Retail Tax Amount</div>
              <div class="retail_price" data-product-target="retailCalculatedRetailPriceTax">
                $ -
              </div>
            </div>
            <div class="col-4">
              <div class="retail_price">Total Retail Price (incl tax)</div>
              <div class="retail_price" data-product-target="retailCalculatedRetailPriceTotal">
                $ -
              </div>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-4">
              <div class="markup_data">Markup Amount</div>
              <div class="markup_data" data-product-target="retailCalculatedMarkupAmount">
                $ -
              </div>
            </div>
             <div class="col-4">
              <div class="markup_data">Profit Amount</div>
              <div class="markup_data" data-product-target="retailCalculatedProfitAmount">
                $ -
              </div>
            </div>
            <div class="col-4">
              <div class="markup_data">Retail Tax Liability</div>
              <div class="markup_data" data-product-target="retailCalculatedRetailTaxLiability">
                $ -
              </div>
            </div>
          </div>
        </div>
        <!-- section for entering amounts via the retail price method -->

        <!-- section for entering amounts via the cost price method -->
        <div class="d-none" data-product-target="calculateCostPriceSection">
          <br />
          <div class="row">
            <div class="col-6">
              <%= f.label @product.cost_price_label %>
              <%= f.text_field :cost_price, placeholder: 'enter the amount which you paid the supplier for this product', value: @existing_variant.display_cost_price, data: { action: "change->product#costPriceDataEntered", target: "product.costPrice" } %>
            </div>
            <div class="col-6">
              <%= f.label "Markup percentage" %>
              <%= f.text_field :markup, placeholder: 'enter the markup percentage to apply to the cost price, e.g. 50%', value: @existing_variant.display_markup, data: { action: "change->product#costPriceDataEntered", target: "product.percentage" } %>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-4">
              <div class="cost_price">Suppliers Cost Price (excl tax)</div>
              <div class="cost_price" data-product-target="calculatedCostPrice">
                $ -
              </div>
            </div>
             <div class="col-4">
              <div class="cost_price">Suppliers Tax Amount</div>
              <div class="cost_price" data-product-target="calculatedCostPriceTax">
                $ -
              </div>
            </div>
            <div class="col-4">
              <div class="cost_price">Suppliers Total Cost Price (incl tax)</div>
              <div class="cost_price" data-product-target="calculatedCostPriceTotal">
                $ -
              </div>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-4">
              <div class="retail_price">Retail Price (excl tax)</div>
              <div class="retail_price" data-product-target="calculatedRetailPrice">
                $ -
              </div>
            </div>
             <div class="col-4">
              <div class="retail_price">Retail Tax Amount</div>
              <div class="retail_price" data-product-target="calculatedRetailPriceTax">
                $ -
              </div>
            </div>
            <div class="col-4">
              <div class="retail_price">Total Retail Price (incl tax)</div>
              <div class="retail_price" data-product-target="calculatedRetailPriceTotal">
                $ -
              </div>
            </div>
          </div>
          <br />
          <div class="row">
            <div class="col-4">
              <div class="markup_data">Markup Amount</div>
              <div class="markup_data" data-product-target="calculatedMarkupAmount">
                $ -
              </div>
            </div>
             <div class="col-4">
              <div class="markup_data">Profit Amount</div>
              <div class="markup_data" data-product-target="calculatedProfitAmount">
                $ -
              </div>
            </div>
            <div class="col-4">
              <div class="markup_data">Retail Tax Liability</div>
              <div class="markup_data" data-product-target="calculatedRetailTaxLiability">
                $ -
              </div>
            </div>
          </div>
        </div>
        <!-- section for entering amounts via the cost price method -->


      </div>
      <br />
      <%= f.submit_button "Save Changes" %>
      <%= link_to "Cancel", catalogue_supplier_path(@product.supplier.id), class: "btn btn-outline-secondary" %>
    <% end %>
  </div>
</div>

app/views/catalogue/variants/index.html.erb
<div class="p-12 mx-auto text-gray-800 max-w-7xl">
  <h2>Find a product</h2>
  <%= simple_form_for :search, url: search_catalogue_variants_path do |f| %>
    <%= f.input :sku_code, as: :string, placeholder: 'search by sku code', input_html: { :value => @query_params['sku'] } %>
    <%= f.input :description, as: :string, placeholder: 'search by product text', input_html: { :value => @query_params['description'] } %>
    <%= f.submit "Search for Product", class: 'btn btn-primary' %>
    <%= link_to "Done", catalogue_index_path, class: "btn btn-secondary" %>
    <%= link_to "Clear", catalogue_variants_path, class: "btn btn-outline-secondary" %>
  <% end %>
  <br />
  <% if @query_params['description'].present? || @query_params['sku'].present? %>
    <h4>Search results</h4>
    <% if @results.present? %>
      <table style="width:100%">
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Sku Code</th>
          <th>Retail Amount (incl. tax)</th>
          <th>Quantity</th>
        </tr>
        <% @results.each do |result| %>
          <tr>
            <td><%= result.display_title %></th>
            <td><%= result.display_with_product_details %></th>
            <td><%= result.sku_code %></th>
            <td><%= result.display_total_retail_price_including_tax %></th>
            <td><%= result.stock_count %></th>
          </tr>
        <% end %>
      </table>
    <% else %>
      <br / >
      <h5>No matches found for query</h5>
    <% end %>
  <% end %>
</div>

app/views/catalogue/variants/show.html.erb
<div class="p-12 mx-auto text-gray-800 max-w-7xl">
  <h2>Variant Details: <%= @existing_variant.display_title %></h2>
  <div data-controller="hello">
    <table style="width:70%">
      <tr>
        <th>Variant Characterstics:</th>
        <td><%= @existing_variant.display_characteristics %></td>
      </tr>
      <tr>
        <th>SKU Code:</th>
        <td><%= @existing_variant.sku_code %></td>
      </tr>
      <tr>
        <th>Published:</th>
        <td><%= @existing_variant.product.display_published %></td>
      </tr>
      <tr>
        <th>Supplier registered for tax?:</th>
        <td><%= @existing_variant.display_supplier_registered_for_sales_tax %></td>
      </tr>
      <tr>
        <th>Prices and Markup as per Parent Product?:</th>
        <td><%= @existing_variant.display_use_product_details %></td>
      </tr>
      <tr><th>&nbsp;</th><td>&nbsp;</td></tr>
      <tr>
        <th>Cost Price:</th>
        <td><%= @existing_variant.display_cost_price %></td>
      </tr>
      <tr>
        <th>Tax Amount:</th>
        <td><%= @existing_variant.display_cost_price_tax_amount %></td>
      </tr>
      <tr>
        <th>Total Cost Price (inclusive sales tax):</th>
        <td><%= @existing_variant.display_total_cost_price %></td>
      </tr>
      <tr><th>&nbsp;</th><td>&nbsp;</td></tr>
      <tr>
        <th>Retail Price (excluding sales tax):</th>
        <td><%= @existing_variant.display_retail_price %></td>
      </tr>
      <tr>
        <th>Applicable Tax:</th>
        <td><%= @existing_variant.display_retail_price_tax_amount %></td>
      </tr>
      <tr>
        <th>Total Retail Price (inclusive sales tax):</th>
        <td><%= @existing_variant.display_total_retail_price_including_tax %></td>
      </tr>
      <tr><th>&nbsp;</th><td>&nbsp;</td></tr>
      <tr>
        <th>Markup on Cost Price:</th>
        <td><%= @existing_variant.display_markup %></td>
      </tr>
      <tr>
        <th>Markup Amount:</th>
        <td><%= @existing_variant.display_retail_mark_up_amount %></td>
      </tr>
      <tr>
        <th>Profit Amount:</th>
        <td><%= @existing_variant.display_profit_amount %></td>
      </tr>
      <tr>
        <th>Retail Tax Liability:</th>
        <td><%= @existing_variant.display_retail_sales_tax_liability_amount %></td>
      </tr>
    </table>
    <br />
      <%= link_to "Back to Products", catalogue_supplier_path(@existing_variant.product.supplier.id), class: "btn btn-primary" %>
  </div>
</div>