config/routes.rb
Rails.application.routes.draw do
#   devise_for :views
#   devise_for :users
#   get "home/index"
#   root to: "home#index"
# end
# Rails.application.routes.draw do
  # devise_for :users
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :views
  get "home/index"
  root to: "home#index"

  resources :sales, only: [:index, :show] do
    get 'all', to: 'sales#all', on: :collection
  end

  resources :customers, only: [:new, :create, :edit, :update, :show, :index, :destroy]
  resources :reports, only: [:index, :show, :edit, :update]
  resources :orders, only: [:new, :create, :update, :show, :destroy] do
    collection do
      get 'new/:items', :action => 'new', :as => 'item_to_be_added_to'
      get 'edit/:items', :action => 'new_customer', :as => 'new_customer_for'
      delete 'remove/:items, :item', :action => 'remove_item', :as => 'remove_item_from'
    end
    resources :receipts, only: [:new], defaults: { format: :pdf }
    resources :payments, only: [:new, :create]
    resources :items, only: [:new, :create, :destroy]
  end
  resources :payments do
    collection do
      get 'new/:items, :customer', :action => 'new_order_payment', :as => 'new_order'
      get 'new/:items', :action => 'new_order_payment', :as => 'new_order_without_customer'
    end
  end

  resources :items, only: [:create]
  resources :catalogue, only: [:index]
  resources :suppliers, only: [:index, :new, :create, :show, :edit, :update]

  namespace :catalogue do
    resources :suppliers, only: [:index, :new, :create, :show] do
      resources :products, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
        resources :variants, only: [:create, :edit, :update, :destroy, :show] do
          get :print, on: :member
        end
        resource :variant do
          collection do
            get "new/:variant_attributes", :action => 'new', :as => 'new', :defaults => { :variant_attributes => "" }
          end
        end
        resources :product_attributes, only: [:new, :create]
        resources :product_attribute_types, only: [:index, :new, :create, :destroy]
      end
    end
    resources :variants do
      collection do
        get 'index/:results, :query_params', :action => 'index', :as => 'index'
        post 'search', :action => 'search', :as => 'search'
      end
    end
  end

  namespace :inventory do
    resources :suppliers, only: [:index, :new, :create, :show] do
      resources :products, only: [] do
        resources :variants, only: [] do
          resources :adjustments, only: [:new, :create, :index]
        end
      end
    end
  end
  resources :inventories, only: [:index]
end

app/models/supplier.rb
# frozen_string_literal: true

class Supplier < ApplicationRecord
  has_many :products, dependent: :destroy
  belongs_to :address

  accepts_nested_attributes_for :address

  # validates_presence_of   :username, :message => 'Please Enter User  Name.'
  validates :name, :phone, presence: true
  validates :sales_tax_registered, inclusion: { in: [true, false] }
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }

  delegate :display_address, to: :address

  def registered_for_sales_tax?
    sales_tax_registered
  end

  def sales_tax_registered_text
    registered_for_sales_tax? ? 'Registed for Sales Tax' : 'Not Registered for Sales Tax'
  end
end

app/controllers/catalogue/suppliers_controller.rb
# frozen_string_literal: true

class Catalogue::SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :supplier, only: %i[index create]

  def index; end

  def show
    @supplier = existing_supplier(id: params['id'])
    @products = @supplier.products
  end

  def create
    if existing_supplier.present?
      redirect_to catalogue_supplier_path(existing_supplier.id)
    else
      flash.now.alert = 'Please select a supplier from the list'
      render(:index, status: :unprocessable_entity)
    end
  end

  private

  def supplier
    @supplier ||= Supplier.new
  end

  def existing_supplier(id: nil)
    supplier_id = id || supplier_params[:id]
    @existing_supplier = Supplier.find_by(id: supplier_id) if supplier_id.present?
  end

  def supplier_params
    params.require(:supplier).permit(:id)
  end
end

app/controllers/inventories_controller.rb
# frozen_string_literal: true

class InventoriesController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/controllers/inventory/adjustments_controller.rb
# frozen_string_literal: true

class Inventory::AdjustmentsController < ApplicationController
  before_action :authenticate_user!

  def index
    @adjustments = variant.stock_adjustments
    @variant = variant
  end

  def new
    @current_user = current_user
    @stock_adjustment = variant.stock_adjustments.new
    @adjustment_types = StockAdjustment.adjustment_types.keys
  end

  def create
    @stock_adjustment = variant.stock_adjustments.new(stock_adjustment_params)
    return render(:new, status: :unprocessable_entity) unless @stock_adjustment.save

    redirect_to inventory_supplier_path(supplier.id)
  end

  private

  def stock_adjustment_params
    params.require(:stock_adjustment).permit(:quantity, :adjustment_type, :user_id)
  end

  def supplier
    @supplier ||= Supplier.find_by(id: params['supplier_id']) if params['supplier_id']
  end

  def product
    @product ||= supplier.products.find_by(id: params['product_id']) if params['product_id']
  end

  def variant
    @variant ||= product.variants.find_by(id: params['variant_id']) if params['variant_id']
  end
end

app/controllers/inventory/suppliers_controller.rb
# frozen_string_literal: true

class Inventory::SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :supplier, only: %i[index create]

  def index; end

  def show
    @supplier = existing_supplier(id: params['id'])
    @products = @supplier.products
  end

  def create
    if existing_supplier.present?
      redirect_to inventory_supplier_path(existing_supplier.id)
    else
      flash.now.alert = 'Please select a supplier from the list'
      render(:index, status: :unprocessable_entity)
    end
  end

  private

  def supplier
    @supplier ||= Supplier.new
  end

  def existing_supplier(id: nil)
    supplier_id = id || supplier_params[:id]
    @existing_supplier = Supplier.find_by(id: supplier_id) if supplier_id.present?
  end

  def supplier_params
    params.require(:supplier).permit(:id)
  end
end

app/controllers/suppliers_controller.rb
# frozen_string_literal: true

class SuppliersController < ApplicationController
  before_action :authenticate_user!
  before_action :existing_supplier, only: %i[edit update]

  def index
    @suppliers = Supplier.all.order(:name)
  end

  def new
    @supplier = Supplier.new
    @supplier.build_address
    @gst_rates = TaxRate.all
  end

  def edit; end

  def create
    @supplier = Supplier.new(supplier_params)
    return render(:new, status: :unprocessable_entity) unless @supplier.save

    redirect_to suppliers_path
  end

  def update
    if @existing_supplier.update(supplier_params)
      redirect_to suppliers_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def existing_supplier
    @existing_supplier = Supplier.find_by(id: params['id'])
  end

  def supplier_params
    params.require(:supplier).permit(:name, :email, :phone, :tax_rate_id, :address_id, :notes, :sales_tax_registered, :abn_number, :bank_account_name, :bank_acount_number, :bank_bsb, :bank_name,
                                     address_attributes: %i[country_id first_line second_line city state postcode])
  end
end

app/helpers/catalogue/suppliers_helper.rb
# frozen_string_literal: true

module Catalogue::SuppliersHelper
end

app/helpers/inventories_helper.rb
# frozen_string_literal: true

module InventoriesHelper
end

app/helpers/inventory/adjustments_helper.rb
# frozen_string_literal: true

module Inventory::AdjustmentsHelper
end

app/helpers/inventory/suppliers_helper.rb
# frozen_string_literal: true

module Inventory::SuppliersHelper
end

app/helpers/suppliers_helper.rb
# frozen_string_literal: true

module SuppliersHelper
end

app/views/inventory/suppliers/index.html.erb
<div class="p-12 mx-auto text-gray-800 max-w-7xl">
  <h2>Receive Stock for a Supplier's Products and Variants</h2>
  <br />
  <%= simple_form_for @supplier, builder: TailwindFormBuilder, class: "mt-6", url: inventory_suppliers_path do |f| %>
    <%= f.label "Select the Supplier then click Next" %>
    <%= f.collection_select :id, Supplier.order(:name),:id,:name, include_blank: true %>
    <br />
    <br />
    <%= f.submit_button "Next" %>
    <%= link_to "Back", inventories_path, class: "btn btn-outline-secondary" %>
  <% end %>
</div>

app/views/inventory/suppliers/show.html.erb
<div class="p-10">
  <h2>Showing Products for <%= @supplier.name %></h2>

  <table class="min-w-full table-auto">
    <thead>
      <tr>
        <th>Product Name / sku</th>
        <th>Description and Variants</th>
        <th>Current Stock Level</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <br />
      <% @products.each do |product| %>
        <tr>
          <td><%= product.title %></td>
          <td><%= product.description %></td>
          <td><%= product.stock_count %></td>
          <td colspan="3">
          </td>
        </tr>
        <tr><td colspan="6">Notes: <%= product.notes %></td></tr>
        <% product.variants.each do |variant| %>
          <tr>
            <td><%= variant.sku_code %></td>
            <td><%= variant.display_characteristics %></td>
            <td><%= variant.stock_count %></td>
            <td colspan="3">
              <%= link_to "Receive Stock", new_inventory_supplier_product_variant_adjustment_path(@supplier.id, product.id, variant.id), class: "btn btn-primary" %>
              <%= link_to "View History", inventory_supplier_product_variant_adjustments_path(@supplier.id, product.id, variant.id), class: "btn btn-secondary" %>
              <%= link_to "Print Labels", print_catalogue_supplier_product_variant_path(@supplier.id, product.id, variant.id), class: "btn btn-outline-secondary", target: :_blank %>
            </td>
          </tr>
        <% end %>
        <tr><td colspan="6"><hr></td></tr>
      <% end %>
    </tbody>
  </table>

  <br />
  <%= link_to "Select another Supplier", inventory_suppliers_path(@supplier.id), class: "btn btn-outline-secondary" %>
  <%= link_to "Back to Catalogue", inventories_path(@supplier.id), class: "btn btn-outline-secondary" %>
</div>