config/routes.rb
Rails.application.routes.draw do
#   devise_for :views
#   devise_for :users
#   get "home/index"
#   root to: "home#index"
# end
# Rails.application.routes.draw do
  # devise_for :users
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :views
  get "home/index"
  root to: "home#index"

  resources :sales, only: [:index, :show] do
    get 'all', to: 'sales#all', on: :collection
  end

  resources :customers, only: [:new, :create, :edit, :update, :show, :index, :destroy]
  resources :reports, only: [:index, :show, :edit, :update]
  resources :orders, only: [:new, :create, :update, :show, :destroy] do
    collection do
      get 'new/:items', :action => 'new', :as => 'item_to_be_added_to'
      get 'edit/:items', :action => 'new_customer', :as => 'new_customer_for'
      delete 'remove/:items, :item', :action => 'remove_item', :as => 'remove_item_from'
    end
    resources :receipts, only: [:new], defaults: { format: :pdf }
    resources :payments, only: [:new, :create]
    resources :items, only: [:new, :create, :destroy]
  end
  resources :payments do
    collection do
      get 'new/:items, :customer', :action => 'new_order_payment', :as => 'new_order'
      get 'new/:items', :action => 'new_order_payment', :as => 'new_order_without_customer'
    end
  end

  resources :items, only: [:create]
  resources :catalogue, only: [:index]
  resources :suppliers, only: [:index, :new, :create, :show, :edit, :update]

  namespace :catalogue do
    resources :suppliers, only: [:index, :new, :create, :show] do
      resources :products, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
        resources :variants, only: [:create, :edit, :update, :destroy, :show] do
          get :print, on: :member
        end
        resource :variant do
          collection do
            get "new/:variant_attributes", :action => 'new', :as => 'new', :defaults => { :variant_attributes => "" }
          end
        end
        resources :product_attributes, only: [:new, :create]
        resources :product_attribute_types, only: [:index, :new, :create, :destroy]
      end
    end
    resources :variants do
      collection do
        get 'index/:results, :query_params', :action => 'index', :as => 'index'
        post 'search', :action => 'search', :as => 'search'
      end
    end
  end

  namespace :inventory do
    resources :suppliers, only: [:index, :new, :create, :show] do
      resources :products, only: [] do
        resources :variants, only: [] do
          resources :adjustments, only: [:new, :create, :index]
        end
      end
    end
  end
  resources :inventories, only: [:index]
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index; end
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
    <!--Card 1-->
    <div class="rounded overflow-hidden shadow-lg content-center">
      <!-- <img class="w-full" src="/mountain.jpg" alt="Mountain"> -->
      <div class="px-6 py-4">
        <div class="mb-4 text-3xl font-black">Point of Sale</div>
        <p class="text-gray-700 text-base">
          Sell Products and Print Receipts
        </p>
      </div>
      <div class="px-6 pt-4 pb-2">
        <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, sales_path %>
      </div>
    </div>
    <!--Card 2-->
    <div class="rounded overflow-hidden shadow-lg">
      <!-- <img class="w-full" src="/river.jpg" alt="River"> -->
      <div class="px-6 py-4">
        <div class="mb-4 text-3xl font-black">Products & Suppliers</div>
        <p class="text-gray-700 text-base">
          <p>Onboard Suppliers, Add or Edit Products and Variants</p>
        </p>
      </div>
      <div class="px-6 pt-4 pb-2">
        <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, catalogue_index_path %>
      </div>
    </div>

    <!--Card 3-->
    <div class="rounded overflow-hidden shadow-lg">
      <!-- <img class="w-full" src="/forest.jpg" alt="Forest"> -->
      <div class="px-6 py-4">
        <div class="mb-4 text-3xl font-black">Inventory</div>
        <p class="text-gray-700 text-base">
          Receive Stock, Handle Returns and Print Labels
        </p>
      </div>
      <div class="px-6 pt-4 pb-2">
        <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, inventories_path %>
      </div>
    </div>
  </div>
<% else %>
  <div class="max-w-lg mx-auto mt-16 text-center max-w-sm rounded overflow-hidden shadow-lg p-10">
    <h1 class="mb-4 text-3xl font-black">Welcome to Poskin!!</h1>
    <p class="text-lg leading-snug">why don't you buy this product??</p>
  </div>
<% end %>