config/routes.rb
Rails.application.routes.draw do
#   devise_for :views
#   devise_for :users
#   get "home/index"
#   root to: "home#index"
# end
# Rails.application.routes.draw do
  # devise_for :users
  devise_for :users do
    delete '/users/sign_out' => 'devise/sessions#destroy'
  end
  devise_for :views
  get "home/index"
  root to: "home#index"

  resources :sales, only: [:index, :show] do
    get 'all', to: 'sales#all', on: :collection
  end

  resources :customers, only: [:new, :create, :edit, :update, :show, :index, :destroy]
  resources :reports, only: [:index, :show, :edit, :update]
  resources :orders, only: [:new, :create, :update, :show, :destroy] do
    collection do
      get 'new/:items', :action => 'new', :as => 'item_to_be_added_to'
      get 'edit/:items', :action => 'new_customer', :as => 'new_customer_for'
      delete 'remove/:items, :item', :action => 'remove_item', :as => 'remove_item_from'
    end
    resources :receipts, only: [:new], defaults: { format: :pdf }
    resources :payments, only: [:new, :create]
    resources :items, only: [:new, :create, :destroy]
  end
  resources :payments do
    collection do
      get 'new/:items, :customer', :action => 'new_order_payment', :as => 'new_order'
      get 'new/:items', :action => 'new_order_payment', :as => 'new_order_without_customer'
    end
  end

  resources :items, only: [:create]
  resources :catalogue, only: [:index]
  resources :suppliers, only: [:index, :new, :create, :show, :edit, :update]

  namespace :catalogue do
    resources :suppliers, only: [:index, :new, :create, :show] do
      resources :products, only: [:index, :new, :create, :edit, :update, :destroy, :show] do
        resources :variants, only: [:create, :edit, :update, :destroy, :show] do
          get :print, on: :member
        end
        resource :variant do
          collection do
            get "new/:variant_attributes", :action => 'new', :as => 'new', :defaults => { :variant_attributes => "" }
          end
        end
        resources :product_attributes, only: [:new, :create]
        resources :product_attribute_types, only: [:index, :new, :create, :destroy]
      end
    end
    resources :variants do
      collection do
        get 'index/:results, :query_params', :action => 'index', :as => 'index'
        post 'search', :action => 'search', :as => 'search'
      end
    end
  end

  namespace :inventory do
    resources :suppliers, only: [:index, :new, :create, :show] do
      resources :products, only: [] do
        resources :variants, only: [] do
          resources :adjustments, only: [:new, :create, :index]
        end
      end
    end
  end
  resources :inventories, only: [:index]
end

app/models/reports/sales.rb
# frozen_string_literal: true

require 'csv'

module Reports
  class SalesReportItem
    include ActiveModel::Attributes
    include ApplicationHelper

    attribute :date, :string
    attribute :order_ref, :string
    attribute :description, :string
    attribute :quantity, :string
    attribute :amounts, :string
    attribute :amount_paid, :string

    def populate_from(item, additional_row=nil, summary_value=nil)
      if item&.class&.name == 'Order' && !additional_row
        self.date = item.display_date
        self.order_ref = item.id
        self.amounts = item.number_of_items == 1 ? item.display_order_price_total_including_tax : nil
        self.description = item.number_of_items > 1 ? nil : item.order_items&.first&.display_name
        self.quantity = item.number_of_items > 1 ? nil : item.number_of_items
        self.amount_paid = item.number_of_items > 1 || (item.has_delivery_charges? || item.discounted?) ? nil : item.display_order_price_total_including_tax
      elsif !additional_row # these are order items, order was for more than 1 item
        self.date = nil
        self.order_ref = nil
        self.amounts = item.display_retail_amount_per_unit_including_tax
        self.description = item.display_name
        self.quantity = item.quantity
        self.amount_paid = nil
      elsif additional_row
        case additional_row
        when :delivery
          self.date = nil
          self.order_ref = nil
          self.amounts = item.display_delivery_amount
          self.description = 'DELIVERY'
          self.quantity = nil
          self.amount_paid = nil
        when :discount
          self.date = nil
          self.order_ref = nil
          self.amounts = item.display_discount_amount
          self.description = 'DISCOUNT'
          self.quantity = nil
          self.amount_paid = nil
        when :total
          self.date = nil
          self.order_ref = nil
          self.amounts = nil
          self.description = 'TOTAL'
          self.quantity = item.number_of_items
          self.amount_paid = item.display_order_price_total_including_tax_with_delivery_or_discount
        when :summary
          self.date = 'SUMMARY TOTAL'
          self.order_ref = nil
          self.amounts = nil
          self.description = nil
          self.quantity = nil
          self.amount_paid = summary_value
        end
      end
    end
  end

  class Sales
    include ActionView::Helpers::NumberHelper

    attr_accessor :from_date, :string
    attr_accessor :to_date, :string
    attr_accessor :orders, :array
    attr_accessor :total_sales_amount, :string

    def initialize
      self.from_date = all_orders.last.created_at.to_date
      self.to_date = all_orders.first.created_at.to_date
      self.orders = orders_for_display
    end

    def to_csv
      CSV.generate do |csv|
        csv << column_names.map{|column_name| column_name.titleize}
        orders.each do |order|
          csv << order.attributes.values_at(*column_names)
       end
      end
    end

    def filename
      "sales-report-#{DateTime.now.strftime("%d%m%Y%H%M")}.csv"
    end

    def partial
      'reports/sales'
    end

    def update_with(params)
      self.from_date = params['from_date'].to_date
      self.to_date = params['to_date'].to_date
      self.orders = orders_for_display
    end

    def column_names
      SalesReportItem.attribute_names
    end

    def all_orders
      @all_orders ||= Order.includes(order_items:[variant:[:product, :stock_adjustments, product_attributes_variants: [:product_attribute]]]).order(created_at: :desc)
    end

    def additional_rows_for(order, additional_row_type, summary=nil)
      sales_report_item_additional_row = SalesReportItem.new
      sales_report_item_additional_row.populate_from(order, additional_row_type, summary)
      sales_report_item_additional_row
    end

    def orders_for_display
      total_sales_amount = 0
      orders_for_display = []
      filtered_orders = all_orders.where(:created_at => self.from_date.beginning_of_day..self.to_date.end_of_day)
      filtered_orders.each do |order|
        next if order.number_of_items < 1
        total_sales_amount += order.order_price_total_including_tax_with_delivery_or_discount
        sales_report_item = SalesReportItem.new
        sales_report_item.populate_from(order)
        orders_for_display << sales_report_item
        if order.number_of_items > 1
          order.order_items.each do |order_item|
            sales_report_item = SalesReportItem.new
            sales_report_item.populate_from(order_item)
            orders_for_display << sales_report_item
          end
          # when the order has more than 1 item we always add total and conditionally add delivery/discount
          if order.has_delivery_charges? || order.discounted?
            orders_for_display << additional_rows_for(order, :delivery) if order.has_delivery_charges?
            orders_for_display << additional_rows_for(order, :discount) if order.discounted?
            # add those additional_rows_for each
          end
          orders_for_display << additional_rows_for(order, :total)
          # always add additional_rows_for for the total
        else
          # when the order has only 1 item we conditionally  add discount/delivery and total
          if order.has_delivery_charges? || order.discounted?
            orders_for_display << additional_rows_for(order, :delivery) if order.has_delivery_charges?
            orders_for_display << additional_rows_for(order, :discount) if order.discounted?
            orders_for_display << additional_rows_for(order, :total)
          end
        end
      end
      # write the summary total line
      display_total_sales_amount = number_to_currency(format('%.2f', total_sales_amount.to_f)) unless total_sales_amount.nil?
      orders_for_display << additional_rows_for(nil, :summary, display_total_sales_amount)
      orders_for_display
    end
  end
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

class SalesController < ApplicationController
  before_action :authenticate_user!
  before_action :remember_page, only: [:index]

  def index; end

  def all
    @orders = Order.includes(:customer, order_items: [variant:[:product]]).where(payment_other_method: nil).order(created_at: :desc)
  end

  def show
    @order = Order.includes(:order_items, :receipts).find_by(id: params['id'])
  end
end

app/helpers/sales_helper.rb
# frozen_string_literal: true

module SalesHelper
end

app/views/sales/all.html.erb
<div class="p-12 mx-auto text-gray-800 max-w-7xl">
  <h2>All Sales</h2>
  <div data-controller="hello">
    <br />
    <table style="width:100%">
      <tr>
        <th>Date</th>
        <th>State</th>
        <th>Order Amount</th>
        <th>Discount</th>
        <th>Delivery</th>
        <th>Total Paid</th>
        <th>Customer Details</th>
        <th></th>
      </tr>
      <% @orders.each do |order| %>
        <tr>
          <td><%= order.display_date %></td>
          <td><%= order.state&.upcase %></td>
          <td><%= order.display_order_price_total_including_tax %></td>
          <td><%= order.display_discount_amount %></td>
          <td><%= order.display_delivery_amount %></td>
          <td><%= order.display_order_price_total_including_tax_with_delivery_or_discount %></td>
          <td><%= order.customer_details_for_receipt %></td>
          <td><%= link_to "View Details", sale_path(order.id), class: "btn btn-primary" %></td>
        </tr>
      <% end %>
      <tr><td colspan="8"></td></tr>
      <tr>
        <th>All Sales</th>
        <th colspan="4">
        <th>$<%= @orders.map(&:order_price_total_including_tax_with_delivery_or_discount).compact.sum.round(2) %></th>
        <th></th>
      </tr>
    </table>
  </div>
</div>

app/views/sales/index.html.erb
<div class="p-12 mx-auto text-gray-800 max-w-7xl">
  <h2>Sales</h2>
</div>
<div class="p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 lg:grid-cols-3 xl:grid-cols-3 gap-5">
  <!--Card 1-->
  <div class="rounded overflow-hidden shadow-lg content-center">
    <!-- <img class="w-full" src="/mountain.jpg" alt="Mountain"> -->
    <div class="px-6 py-4">
      <div class="mb-4 text-3xl font-black">Register Sale</div>
      <p class="text-gray-700 text-base">
        Add Products to Sale and Print Receipt
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">

      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, new_order_path, data: {turbo_method: :get} %>

    </div>
  </div>
  <!--Card 2-->
  <div class="rounded overflow-hidden shadow-lg">
    <!-- <img class="w-full" src="/river.jpg" alt="River"> -->
    <div class="px-6 py-4">
      <div class="mb-4 text-3xl font-black">View Sales</div>
      <p class="text-gray-700 text-base">
        View existing sales
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, all_sales_path %>
    </div>
  </div>
  <!--Card 3-->
  <div class="rounded overflow-hidden shadow-lg">
    <!-- <img class="w-full" src="/river.jpg" alt="River"> -->
    <div class="px-6 py-4">
      <div class="mb-4 text-3xl font-black">Customers</div>
      <p class="text-gray-700 text-base">
        Find and Update Customers Details
      </p>
    </div>
    <div class="px-6 pt-4 pb-2">
      <%= link_to '<button class="bg-blue-500 hover:bg-blue-700 text-white font-bold w-1/3 lg:w-full py-2">Continue</button>'.html_safe, customers_path %>
    </div>
  </div>
</div>

app/views/sales/show.html.erb
<div class="p-12 mx-auto text-gray-800 max-w-7xl">
  <h2>Sales Details for Order: <%= @order.id %></h2>
  <div data-controller="hello">
    <table style="width:50%">
      <tr>
        <th>State:</th>
        <td><%= @order.state&.upcase %></td>
      </tr>
      <tr>
        <th>Payment Method:</th>
        <td><%= @order.payment_method&.titleize %></td>
      </tr>
      <tr>
        <th>Date:</th>
        <td><%= @order.display_date %></td>
      </tr>
      <tr>
        <th>Customer Details:</th>
        <td><%= @order.customer_details_for_receipt %></td>
      </tr>
    </table>
    <br />
    <table style="width:100%">
      <tr>
        <th>Items</th>
        <th>Price per Item (excl. Tax)</th>
        <th>Total (excl. Tax)</th>
        <th>Tax Amount</th>
        <th>Payment Amount (incl. Tax)</th>
        <th></th>
      </tr>
      <% @order.order_items.each do |item| %>
        <tr>
          <td><%= item.invoice_display_details %></td>
          <td><%= item.display_retail_amount_per_unit %></td>
          <td><%= item.display_retail_amount %></td>
          <td><%= item.display_retail_amount_tax %></td>
          <td><%= item.display_total_retail_amount %></td>
        </tr>
      <% end %>
      <% if @order.manual_order? %>
        <% if @order.receipts.first.item_one_name.present? %>
          <tr>
            <td><%= @order.receipts.first.item_one_name %></td>
            <td></td>
            <% if @order.receipts.first.old_method? %>
              <td>$<%= format('%.2f',@order.receipts.first.amount_one.to_f / 100 )%></td><td></td><td></td>
            <% else %>
              <td></td><td></td><td>$<%= format('%.2f',@order.receipts.first.amount_one.to_f / 100) %></td>
            <% end %>
          </tr>
        <% end %>
        <% if @order.receipts.first.item_two_name.present? %>
          <tr>
            <td><%= @order.receipts.first.item_two_name %></td>
            <td></td>
            <% if @order.receipts.first.old_method? %>
              <td>$<%= format('%.2f',@order.receipts.first.amount_two.to_f / 100) %></td><td></td><td></td>
            <% else %>
              <td></td><td></td><td>$<%= format('%.2f',@order.receipts.first.amount_two.to_f / 100) %></td>
            <% end %>
          </tr>
        <% end %>
        <% if @order.receipts.first.item_three_name.present? %>
          <tr>
            <td><%= @order.receipts.first.item_three_name %></td>
            <td></td>
            <% if @order.receipts.first.old_method? %>
              <td>$<%= format('%.2f',@order.receipts.first.amount_three.to_f / 100) %></td><td></td><td></td>
            <% else %>
              <td></td><td></td><td>$<%= format('%.2f',@order.receipts.first.amount_three.to_f / 100) %></td>
            <% end %>
          </tr>
        <% end %>
        <% if @order.receipts.first.item_four_name.present? %>
           <tr>
            <td><%= @order.receipts.first.item_four_name %></td>
            <td></td>
            <% if @order.receipts.first.old_method? %>
              <td>$<%= format('%.2f',@order.receipts.first.amount_four.to_f / 100) %></td><td></td><td></td>
            <% else %>
              <td></td><td></td><td>$<%= format('%.2f',@order.receipts.first.amount_four.to_f / 100) %></td>
            <% end %>
          </tr>
        <% end %>
      <% end %>
      <tr><td>&nbsp;</td></tr>
      <tr>
        <th>Order Total</th>
        <th></th>
        <% if @order.manual_order? %>
          <th><%= @order.receipts.first.display_total_amount %></th>
          <th><%= @order.receipts.first.display_tax_amount %></th>
          <th><%= @order.receipts.first.display_total_amount_including_tax %></th>
        <% else %>
          <th><%= @order.display_order_price_total %></th>
          <th><%= @order.display_order_tax_total %></th>
          <th><%= @order.display_order_price_total_including_tax %></th>
        <% end %>
      </tr>
      <% if @order.discounted? %>
        <tr>
          <th>Discount Amount</th>
          <th></th>
          <th></th>
          <th></th>
          <th><%= @order.display_discount_amount %></th>
        </tr>
      <% end %>
      <% if @order.has_delivery_charges? %>
        <tr>
          <th>Delivery Charges</th>
          <th></th>
          <th></th>
          <th></th>
          <th><%= @order.display_delivery_amount %></th>
        </tr>
      <% end %>
      <tr>
        <th>Total Amount Paid</th>
        <th></th>
        <th></th>
        <th></th>
        <th><%= @order.display_order_price_total_including_tax_with_delivery_or_discount %></th>
      </tr>
    </table>
    <br />
      <%= link_to "Back", all_sales_path, class: "btn btn-primary" %>
      <%= link_to "Print Receipt", new_order_receipt_path(@order, customer_name: false), target: "_blank", class: "btn btn-secondary" %>
      <% if @order.customer.present? %>
        <%= link_to "Print with Customer Name", new_order_receipt_path(@order, customer_name: true), target: "_blank", class: "btn btn-secondary" %>
      <% end %>
  </div>
</div>